spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
  profiles:
    active: "loadInitialData"
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: szczepanskikrzysztof074@gmail.com
    password: kljj nfsl zhwd iaok
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
server:
  port: 2101
